base:
  is_dev : false
out_dir : .  # 输出目录
url_tag : json # web url tag(json,db(https://github.com/google/go-querystring))
language :  # 语言(English,中 文)
db_tag : gorm # 数据库标签(gorm,db)
simple : false # 简单输出(默认gorm标签不输出)
is_out_sql : false # 是否输出 sql 原信息
is_out_func : false # 是否输出 快捷函数
is_web_tag : true # 是否打web标记(json标记前提条件)
is_web_tag_pk_hidden: false # web标记是否隐藏主键
is_foreign_key : true # 是否导出外键关联
is_gui : false # 是否ui模式显示
is_table_name : true # 是否直接生成表名,列名
is_null_to_point : false # 数据库默认 'DEFAULT NULL' 时设置结构为指针类型
table_prefix : "" # 表前缀, 如果有则使用, 没有留空
db_info:
  host : 192.168.3.53 # type=1的时候，host为yml文件全路径
  port : 3355
  username : cishop
  password : fuyuan1906
  database : service_items_go
  type: 0 # 数据库类型:0:mysql , 1:sqlite , 2:mssql
self_type_define: # Custom data type mapping
  datetime: DateTime
out_file_name: "" # Custom build file name
web_tag_type: 1 # json tag 0: Small Camel-Case 1: _